// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXhbHjQgI-AtRyfj_NS_Ch3piSGVcZoY',
    appId: '1:765042782141:web:0f757182049ba0d43d6cd4',
    messagingSenderId: '765042782141',
    projectId: 'gajgaji',
    authDomain: 'gajgaji.firebaseapp.com',
    storageBucket: 'gajgaji.appspot.com',
    measurementId: 'G-79MSJ78JC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv908arI5BdN2SzD4MBAWWJaqvmCggy6Q',
    appId: '1:765042782141:android:968492210989a69a3d6cd4',
    messagingSenderId: '765042782141',
    projectId: 'gajgaji',
    storageBucket: 'gajgaji.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmF2v3L1MRk61PGJfcMruuoxMRvtRs7PY',
    appId: '1:765042782141:ios:086104ab47ebf71b3d6cd4',
    messagingSenderId: '765042782141',
    projectId: 'gajgaji',
    storageBucket: 'gajgaji.appspot.com',
    iosClientId: '765042782141-72m7ojtoqt16mu7dpu14r26n74sj5o3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gajgaji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmF2v3L1MRk61PGJfcMruuoxMRvtRs7PY',
    appId: '1:765042782141:ios:086104ab47ebf71b3d6cd4',
    messagingSenderId: '765042782141',
    projectId: 'gajgaji',
    storageBucket: 'gajgaji.appspot.com',
    iosClientId: '765042782141-72m7ojtoqt16mu7dpu14r26n74sj5o3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.gajgaji',
  );
}
